In [3]:
import numpy as np

In [4]:
arr = np.array([2,5,3,4,6])

In [5]:
arr.dtype

dtype('int32')

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [9]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [10]:
emp = np.empty((4,6))

In [11]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.60218627e-306, 7.56587585e-307, 7.56593017e-307],
       [1.24610383e-306, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22522597e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 6.89805151e-307,
        1.78020169e-306, 1.42410974e-306, 2.22522596e-306]])

In [12]:
ide = np.identity(3)

In [13]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
ide.shape

(3, 3)

In [16]:
x = [[1,2,3],[4,3,1],[5,4,2]]

In [17]:
ar = np.array(x)

In [18]:
ar

array([[1, 2, 3],
       [4, 3, 1],
       [5, 4, 2]])

In [19]:
ar.sum(axis=0)

array([10,  9,  6])

In [20]:
ar

array([[1, 2, 3],
       [4, 3, 1],
       [5, 4, 2]])

In [21]:
ar.sum(axis=1)

array([ 6,  8, 11])

In [22]:
for item in ar.flat:
    print(item)

1
2
3
4
3
1
5
4
2


In [23]:
ar.nbytes

36

In [24]:
ar


array([[1, 2, 3],
       [4, 3, 1],
       [5, 4, 2]])

In [25]:
ar.argmin()

0

In [26]:
ar.argmax()

6

In [27]:
ar.argmax(axis=0)

array([2, 2, 0], dtype=int64)

In [28]:
ar.argsort(axis=0)

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 0]], dtype=int64)

In [29]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [2, 1, 0]], dtype=int64)

In [30]:
ar.ravel()

array([1, 2, 3, 4, 3, 1, 5, 4, 2])

In [31]:
ar.sum()

25

In [32]:
ar.max()

5

In [33]:
ar.min()

1